----------------------------------------
ActivityId: 3c29bf26-57d2-45de-8fd6-f9beb778dc4a

Timestamp: 18.11.2024 13:16:02

Message: HandlingInstanceID: 7b0c1fd0-4921-40a6-bc2f-4d88745f17b5
An exception of type 'Telerik.OpenAccess.OpenAccessException' occurred and was caught.
--------------------------------------------------------------------------------------
11/18/2024 14:16:02
Type : Telerik.OpenAccess.OpenAccessException, Telerik.OpenAccess, Version=2020.0.428.1, Culture=neutral, PublicKeyToken=7ce17eeaf1d59342
Message : ‹‹‹Telerik.OpenAccess.RT.sql.SQLException: Login failed for user 'IlyaMaisiuk'.›››
Source : Telerik.OpenAccess
Help link : 
InnerExceptions : ‹‹‹System.Exception[]›››
FailedObject : 
BackendError : ‹‹‹Telerik.OpenAccess.RT.sql.SQLException: Login failed for user 'IlyaMaisiuk'. ---> System.Data.SqlClient.SqlException: Login failed for user 'IlyaMaisiuk'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at OpenAccessRuntime.Intellitrace.OpenConnection(DbConnection connection, String connectionString, String id)
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   --- End of inner exception stack trace ---
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   at OpenAccessRuntime.DataObjects.tools.ant.DatabaseCreationTask.createDatabase()›››
Reason : ‹‹‹Runtime›››
CanRetry : ‹‹‹True›››
Data : ‹‹‹System.Collections.ListDictionaryInternal›››
TargetSite : ‹‹‹Void ThrowException(System.Exception)›››
HResult : ‹‹‹-2146233088›››
Stack Trace :    at Telerik.OpenAccess.SPI.Backends.ThrowException(Exception e)
   at OpenAccessRuntime.ExceptionWrapper.Throw()
   at OpenAccessRuntime.DataObjects.tools.ant.DataObjectsTaskBase.throwBuildException(String str, Exception e)
   at OpenAccessRuntime.DataObjects.tools.ant.DatabaseCreationTask.createDatabase()
   at OpenAccessRuntime.OpenAccessSchemaAdapter.CreateDatabase(Boolean checkOnly)
   at OpenAccessRuntime.SchemaHandlerImpl.Telerik.OpenAccess.ISchemaHandler.CreateDatabase()
   at Telerik.Sitefinity.Data.OA.OpenAccessConnection.UpgradeDatabaseSchema(ISchemaHandler schemaHandler, OpenAccessConnection connection)
   at Telerik.Sitefinity.Data.OA.OpenAccessConnection.UpgradeDatabase(Database database, OpenAccessConnection connection)
   at Telerik.Sitefinity.Data.OA.OpenAccessConnection.GetAndUpgradeMetadataDatabase(IConnectionStringSettings connectionSettings, OpenAccessConnection oaConnection, MetadataContainer metadataContainer, String appName, String moduleName, String& connString, Int32& previousBuild, Boolean isSecondCall)

Additional Info:

MachineName : BRIMITPL-IMO
TimeStamp : 18.11.2024 13:16:02
FullName : Telerik.Sitefinity.Utilities, Version=15.2.8400.0, Culture=neutral, PublicKeyToken=b28c218413bdf563
AppDomainName : /LM/W3SVC/2/ROOT-1-133764092455929219
ThreadIdentity : 
WindowsIdentity : BRIMITPL-IMO\local-admin
Requested URL : http://127.0.0.1/
	Inner Exception
	---------------
	Type : Telerik.OpenAccess.RT.sql.SQLException, Telerik.OpenAccess.Runtime, Version=2020.0.428.1, Culture=neutral, PublicKeyToken=7ce17eeaf1d59342
	Message : ‹‹‹Login failed for user 'IlyaMaisiuk'.›››
	Source : Telerik.OpenAccess.Runtime
	Help link : 
	ErrorCode : ‹‹‹18456›››
	ArrayBindIndex : ‹‹‹-1›››
	Number : ‹‹‹18456›››
	ObjectId : 
	Description : ‹‹‹Login failed for user 'IlyaMaisiuk'.›››
	Data : ‹‹‹System.Collections.ListDictionaryInternal›››
	TargetSite : ‹‹‹Telerik.OpenAccess.RT.sql.Connection connect(Telerik.OpenAccess.Config.Sql.ConnectionString, Telerik.OpenAccess.SPI.PropertySet, Telerik.OpenAccess.ConnectionPoolType, OpenAccessRuntime.logging.LogEventStore)›››
	HResult : ‹‹‹-2146233088›››
	Stack Trace :    at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
	   at OpenAccessRuntime.DataObjects.tools.ant.DatabaseCreationTask.createDatabase()

		Inner Exception
		---------------
		Type : System.Data.SqlClient.SqlException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
		Message : ‹‹‹Login failed for user 'IlyaMaisiuk'.›››
		Source : .Net SqlClient Data Provider
		Help link : 
		Errors : ‹‹‹System.Data.SqlClient.SqlErrorCollection›››
		ClientConnectionId : ‹‹‹8d0a19db-dc2c-4982-bf23-36d5ab29b660›››
		Class : ‹‹‹14›››
		LineNumber : ‹‹‹65536›››
		Number : ‹‹‹18456›››
		Procedure : ‹‹‹›››
		Server : ‹‹‹tcp:sitefinityserver.database.windows.net,1433›››
		State : ‹‹‹1›››
		ErrorCode : ‹‹‹-2146232060›››
		Data : ‹‹‹System.Collections.ListDictionaryInternal›››
		TargetSite : ‹‹‹Void .ctor(System.Data.ProviderBase.DbConnectionPoolIdentity, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SqlCredential, System.Object, System.String, System.Security.SecureString, Boolean, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SessionData, System.Data.ProviderBase.DbConnectionPool, System.String, Boolean, System.Data.SqlClient.SqlAuthenticationProviderManager)›››
		HResult : ‹‹‹-2146232060›››
		Stack Trace :    at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
		   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
		   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
		   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
		   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
		   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
		   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
		   at System.Data.SqlClient.SqlConnection.Open()
		   at OpenAccessRuntime.Intellitrace.OpenConnection(DbConnection connection, String connectionString, String id)
		   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)



Category: ErrorLog

Priority: 0

EventId: 9010

Severity: Warning

Title:Enterprise Library Exception Handling

Machine: BRIMITPL-IMO

App Domain: /LM/W3SVC/2/ROOT-1-133764092455929219

ProcessId: 18428

Process Name: C:\Program Files\IIS Express\iisexpress.exe

Thread Name: 

Win32 ThreadId:23508

Extended Properties: 
----------------------------------------
----------------------------------------
ActivityId: 3c29bf26-57d2-45de-8fd6-f9beb778dc4a

Timestamp: 18.11.2024 13:16:13

Message: HandlingInstanceID: d4215729-39b8-4f7c-9d8e-689fd37a3cdf
An exception of type 'Telerik.OpenAccess.Exceptions.DataStoreException' occurred and was caught.
------------------------------------------------------------------------------------------------
11/18/2024 14:16:13
Type : Telerik.OpenAccess.Exceptions.DataStoreException, Telerik.OpenAccess, Version=2020.0.428.1, Culture=neutral, PublicKeyToken=7ce17eeaf1d59342
Message : ‹‹‹Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of 'B22D3328-CF57-4E1C-9F03-61F70A77EFF5'. Telerik.OpenAccess.RT.sql.SQLException: Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of 'B22D3328-CF57-4E1C-9F03-61F70A77EFF5'. ---> System.Data.SqlClient.SqlException: Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of 'B22D3328-CF57-4E1C-9F03-61F70A77EFF5'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at OpenAccessRuntime.Intellitrace.OpenConnection(DbConnection connection, String connectionString, String id)
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   --- End of inner exception stack trace ---
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   at OpenAccessRuntime.Relational.sql.SqlDriver.InitializeFor(ConnectionString connectionString, Boolean noConnect, PropertySet props, DBDriver& driver, Connection& conn, ConnectionPoolType poolType)›››
Source : Unity_ILEmit_DynamicClasses
Help link : 
InnerExceptions : ‹‹‹System.Exception[]›››
FailedObject : 
BackendError : ‹‹‹Telerik.OpenAccess.RT.sql.SQLException: Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of 'B22D3328-CF57-4E1C-9F03-61F70A77EFF5'. ---> System.Data.SqlClient.SqlException: Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of 'B22D3328-CF57-4E1C-9F03-61F70A77EFF5'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at OpenAccessRuntime.Intellitrace.OpenConnection(DbConnection connection, String connectionString, String id)
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   --- End of inner exception stack trace ---
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   at OpenAccessRuntime.Relational.sql.SqlDriver.InitializeFor(ConnectionString connectionString, Boolean noConnect, PropertySet props, DBDriver& driver, Connection& conn, ConnectionPoolType poolType)›››
Reason : ‹‹‹Runtime›››
CanRetry : ‹‹‹False›››
Data : ‹‹‹System.Collections.ListDictionaryInternal›››
TargetSite : ‹‹‹Void Initialize(System.String, System.Collections.Specialized.NameValueCollection, System.Type)›››
HResult : ‹‹‹-2146233088›››
Stack Trace :    at DynamicModule.ns.Wrapped_OpenAccessMetaDataProvider_56adb7e0f6784e8b9dae36e76b4acf2d.Initialize(String providerName, NameValueCollection config, Type managerType)
   at Telerik.Sitefinity.Data.ManagerBase`1.InstantiateProvider(IDataProviderSettings providerSettings, Type providerType, ExceptionPolicyName policy, Type managerType)

Additional Info:

MachineName : BRIMITPL-IMO
TimeStamp : 18.11.2024 13:16:13
FullName : Telerik.Sitefinity.Utilities, Version=15.2.8400.0, Culture=neutral, PublicKeyToken=b28c218413bdf563
AppDomainName : /LM/W3SVC/2/ROOT-1-133764092455929219
ThreadIdentity : 
WindowsIdentity : BRIMITPL-IMO\local-admin
Requested URL : http://127.0.0.1/
	Inner Exception
	---------------
	Type : Telerik.OpenAccess.RT.sql.SQLException, Telerik.OpenAccess.Runtime, Version=2020.0.428.1, Culture=neutral, PublicKeyToken=7ce17eeaf1d59342
	Message : ‹‹‹Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of 'B22D3328-CF57-4E1C-9F03-61F70A77EFF5'.›››
	Source : Telerik.OpenAccess.Runtime
	Help link : 
	ErrorCode : ‹‹‹40613›››
	ArrayBindIndex : ‹‹‹-1›››
	Number : ‹‹‹40613›››
	ObjectId : 
	Description : ‹‹‹Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of 'B22D3328-CF57-4E1C-9F03-61F70A77EFF5'.›››
	Data : ‹‹‹System.Collections.ListDictionaryInternal›››
	TargetSite : ‹‹‹Telerik.OpenAccess.RT.sql.Connection connect(Telerik.OpenAccess.Config.Sql.ConnectionString, Telerik.OpenAccess.SPI.PropertySet, Telerik.OpenAccess.ConnectionPoolType, OpenAccessRuntime.logging.LogEventStore)›››
	HResult : ‹‹‹-2146233088›››
	Stack Trace :    at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
	   at OpenAccessRuntime.Relational.sql.SqlDriver.InitializeFor(ConnectionString connectionString, Boolean noConnect, PropertySet props, DBDriver& driver, Connection& conn, ConnectionPoolType poolType)

		Inner Exception
		---------------
		Type : System.Data.SqlClient.SqlException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
		Message : ‹‹‹Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of 'B22D3328-CF57-4E1C-9F03-61F70A77EFF5'.›››
		Source : .Net SqlClient Data Provider
		Help link : 
		Errors : ‹‹‹System.Data.SqlClient.SqlErrorCollection›››
		ClientConnectionId : ‹‹‹6a632c1a-5b58-4244-ade3-af0407f8ffd0›››
		Class : ‹‹‹14›››
		LineNumber : ‹‹‹65536›››
		Number : ‹‹‹40613›››
		Procedure : ‹‹‹›››
		Server : ‹‹‹tcp:sitefinityserver.database.windows.net,1433›››
		State : ‹‹‹1›››
		ErrorCode : ‹‹‹-2146232060›››
		Data : ‹‹‹System.Collections.ListDictionaryInternal›››
		TargetSite : ‹‹‹Void .ctor(System.Data.ProviderBase.DbConnectionPoolIdentity, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SqlCredential, System.Object, System.String, System.Security.SecureString, Boolean, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SessionData, System.Data.ProviderBase.DbConnectionPool, System.String, Boolean, System.Data.SqlClient.SqlAuthenticationProviderManager)›››
		HResult : ‹‹‹-2146232060›››
		Stack Trace :    at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
		   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
		   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
		   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
		   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
		   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
		   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
		   at System.Data.SqlClient.SqlConnection.Open()
		   at OpenAccessRuntime.Intellitrace.OpenConnection(DbConnection connection, String connectionString, String id)
		   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)



Category: ErrorLog

Priority: 0

EventId: 9010

Severity: Warning

Title:Enterprise Library Exception Handling

Machine: BRIMITPL-IMO

App Domain: /LM/W3SVC/2/ROOT-1-133764092455929219

ProcessId: 18428

Process Name: C:\Program Files\IIS Express\iisexpress.exe

Thread Name: 

Win32 ThreadId:23508

Extended Properties: 
----------------------------------------
----------------------------------------
ActivityId: 3c29bf26-57d2-45de-8fd6-f9beb778dc4a

Timestamp: 18.11.2024 13:16:47

Message: HandlingInstanceID: 0e900251-112e-4bdc-8e33-0676a9549ac4
An exception of type 'Telerik.OpenAccess.OpenAccessException' occurred and was caught.
--------------------------------------------------------------------------------------
11/18/2024 14:16:47
Type : Telerik.OpenAccess.OpenAccessException, Telerik.OpenAccess, Version=2020.0.428.1, Culture=neutral, PublicKeyToken=7ce17eeaf1d59342
Message : ‹‹‹Telerik.OpenAccess.RT.sql.SQLException: Login failed for user 'IlyaMaisiuk'.›››
Source : Telerik.OpenAccess
Help link : 
InnerExceptions : ‹‹‹System.Exception[]›››
FailedObject : 
BackendError : ‹‹‹Telerik.OpenAccess.RT.sql.SQLException: Login failed for user 'IlyaMaisiuk'. ---> System.Data.SqlClient.SqlException: Login failed for user 'IlyaMaisiuk'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at OpenAccessRuntime.Intellitrace.OpenConnection(DbConnection connection, String connectionString, String id)
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   --- End of inner exception stack trace ---
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   at OpenAccessRuntime.DataObjects.tools.ant.DatabaseCreationTask.createDatabase()›››
Reason : ‹‹‹Runtime›››
CanRetry : ‹‹‹True›››
Data : ‹‹‹System.Collections.ListDictionaryInternal›››
TargetSite : ‹‹‹Void ThrowException(System.Exception)›››
HResult : ‹‹‹-2146233088›››
Stack Trace :    at Telerik.OpenAccess.SPI.Backends.ThrowException(Exception e)
   at OpenAccessRuntime.ExceptionWrapper.Throw()
   at OpenAccessRuntime.DataObjects.tools.ant.DataObjectsTaskBase.throwBuildException(String str, Exception e)
   at OpenAccessRuntime.DataObjects.tools.ant.DatabaseCreationTask.createDatabase()
   at OpenAccessRuntime.OpenAccessSchemaAdapter.CreateDatabase(Boolean checkOnly)
   at OpenAccessRuntime.SchemaHandlerImpl.Telerik.OpenAccess.ISchemaHandler.CreateDatabase()
   at Telerik.Sitefinity.Data.OA.OpenAccessConnection.UpgradeDatabaseSchema(ISchemaHandler schemaHandler, OpenAccessConnection connection)
   at Telerik.Sitefinity.Data.OA.OpenAccessConnection.UpgradeDatabase(Database database, OpenAccessConnection connection)
   at Telerik.Sitefinity.Data.OA.OpenAccessConnection.GetAndUpgradeMetadataDatabase(IConnectionStringSettings connectionSettings, OpenAccessConnection oaConnection, MetadataContainer metadataContainer, String appName, String moduleName, String& connString, Int32& previousBuild, Boolean isSecondCall)

Additional Info:

MachineName : BRIMITPL-IMO
TimeStamp : 18.11.2024 13:16:47
FullName : Telerik.Sitefinity.Utilities, Version=15.2.8400.0, Culture=neutral, PublicKeyToken=b28c218413bdf563
AppDomainName : /LM/W3SVC/2/ROOT-1-133764092455929219
ThreadIdentity : 
WindowsIdentity : BRIMITPL-IMO\local-admin
Requested URL : http://127.0.0.1/
	Inner Exception
	---------------
	Type : Telerik.OpenAccess.RT.sql.SQLException, Telerik.OpenAccess.Runtime, Version=2020.0.428.1, Culture=neutral, PublicKeyToken=7ce17eeaf1d59342
	Message : ‹‹‹Login failed for user 'IlyaMaisiuk'.›››
	Source : Telerik.OpenAccess.Runtime
	Help link : 
	ErrorCode : ‹‹‹18456›››
	ArrayBindIndex : ‹‹‹-1›››
	Number : ‹‹‹18456›››
	ObjectId : 
	Description : ‹‹‹Login failed for user 'IlyaMaisiuk'.›››
	Data : ‹‹‹System.Collections.ListDictionaryInternal›››
	TargetSite : ‹‹‹Telerik.OpenAccess.RT.sql.Connection connect(Telerik.OpenAccess.Config.Sql.ConnectionString, Telerik.OpenAccess.SPI.PropertySet, Telerik.OpenAccess.ConnectionPoolType, OpenAccessRuntime.logging.LogEventStore)›››
	HResult : ‹‹‹-2146233088›››
	Stack Trace :    at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
	   at OpenAccessRuntime.DataObjects.tools.ant.DatabaseCreationTask.createDatabase()

		Inner Exception
		---------------
		Type : System.Data.SqlClient.SqlException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
		Message : ‹‹‹Login failed for user 'IlyaMaisiuk'.›››
		Source : .Net SqlClient Data Provider
		Help link : 
		Errors : ‹‹‹System.Data.SqlClient.SqlErrorCollection›››
		ClientConnectionId : ‹‹‹49e65d24-8b86-46c3-aa41-0bd8646744b7›››
		Class : ‹‹‹14›››
		LineNumber : ‹‹‹65536›››
		Number : ‹‹‹18456›››
		Procedure : ‹‹‹›››
		Server : ‹‹‹tcp:sitefinityserver.database.windows.net,1433›››
		State : ‹‹‹1›››
		ErrorCode : ‹‹‹-2146232060›››
		Data : ‹‹‹System.Collections.ListDictionaryInternal›››
		TargetSite : ‹‹‹Void .ctor(System.Data.ProviderBase.DbConnectionPoolIdentity, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SqlCredential, System.Object, System.String, System.Security.SecureString, Boolean, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SessionData, System.Data.ProviderBase.DbConnectionPool, System.String, Boolean, System.Data.SqlClient.SqlAuthenticationProviderManager)›››
		HResult : ‹‹‹-2146232060›››
		Stack Trace :    at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
		   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
		   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
		   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
		   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
		   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
		   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
		   at System.Data.SqlClient.SqlConnection.Open()
		   at OpenAccessRuntime.Intellitrace.OpenConnection(DbConnection connection, String connectionString, String id)
		   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)



Category: ErrorLog

Priority: 0

EventId: 9010

Severity: Warning

Title:Enterprise Library Exception Handling

Machine: BRIMITPL-IMO

App Domain: /LM/W3SVC/2/ROOT-1-133764092455929219

ProcessId: 18428

Process Name: C:\Program Files\IIS Express\iisexpress.exe

Thread Name: 

Win32 ThreadId:23508

Extended Properties: 
----------------------------------------
----------------------------------------
ActivityId: 3c29bf26-57d2-45de-8fd6-f9beb778dc4a

Timestamp: 18.11.2024 13:16:58

Message: HandlingInstanceID: 727a69d2-9132-4c8e-bed0-98ee2168238d
An exception of type 'Telerik.OpenAccess.Exceptions.DataStoreException' occurred and was caught.
------------------------------------------------------------------------------------------------
11/18/2024 14:16:58
Type : Telerik.OpenAccess.Exceptions.DataStoreException, Telerik.OpenAccess, Version=2020.0.428.1, Culture=neutral, PublicKeyToken=7ce17eeaf1d59342
Message : ‹‹‹Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '8EB0F76A-793D-44A4-8AF1-7D7DBD2431CF'. Telerik.OpenAccess.RT.sql.SQLException: Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '8EB0F76A-793D-44A4-8AF1-7D7DBD2431CF'. ---> System.Data.SqlClient.SqlException: Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '8EB0F76A-793D-44A4-8AF1-7D7DBD2431CF'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at OpenAccessRuntime.Intellitrace.OpenConnection(DbConnection connection, String connectionString, String id)
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   --- End of inner exception stack trace ---
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   at OpenAccessRuntime.Relational.sql.SqlDriver.InitializeFor(ConnectionString connectionString, Boolean noConnect, PropertySet props, DBDriver& driver, Connection& conn, ConnectionPoolType poolType)›››
Source : Unity_ILEmit_DynamicClasses
Help link : 
InnerExceptions : ‹‹‹System.Exception[]›››
FailedObject : 
BackendError : ‹‹‹Telerik.OpenAccess.RT.sql.SQLException: Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '8EB0F76A-793D-44A4-8AF1-7D7DBD2431CF'. ---> System.Data.SqlClient.SqlException: Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '8EB0F76A-793D-44A4-8AF1-7D7DBD2431CF'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at OpenAccessRuntime.Intellitrace.OpenConnection(DbConnection connection, String connectionString, String id)
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   --- End of inner exception stack trace ---
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   at OpenAccessRuntime.Relational.sql.SqlDriver.InitializeFor(ConnectionString connectionString, Boolean noConnect, PropertySet props, DBDriver& driver, Connection& conn, ConnectionPoolType poolType)›››
Reason : ‹‹‹Runtime›››
CanRetry : ‹‹‹False›››
Data : ‹‹‹System.Collections.ListDictionaryInternal›››
TargetSite : ‹‹‹Void Initialize(System.String, System.Collections.Specialized.NameValueCollection, System.Type)›››
HResult : ‹‹‹-2146233088›››
Stack Trace :    at DynamicModule.ns.Wrapped_OpenAccessMetaDataProvider_56adb7e0f6784e8b9dae36e76b4acf2d.Initialize(String providerName, NameValueCollection config, Type managerType)
   at Telerik.Sitefinity.Data.ManagerBase`1.InstantiateProvider(IDataProviderSettings providerSettings, Type providerType, ExceptionPolicyName policy, Type managerType)

Additional Info:

MachineName : BRIMITPL-IMO
TimeStamp : 18.11.2024 13:16:58
FullName : Telerik.Sitefinity.Utilities, Version=15.2.8400.0, Culture=neutral, PublicKeyToken=b28c218413bdf563
AppDomainName : /LM/W3SVC/2/ROOT-1-133764092455929219
ThreadIdentity : 
WindowsIdentity : BRIMITPL-IMO\local-admin
Requested URL : http://127.0.0.1/
	Inner Exception
	---------------
	Type : Telerik.OpenAccess.RT.sql.SQLException, Telerik.OpenAccess.Runtime, Version=2020.0.428.1, Culture=neutral, PublicKeyToken=7ce17eeaf1d59342
	Message : ‹‹‹Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '8EB0F76A-793D-44A4-8AF1-7D7DBD2431CF'.›››
	Source : Telerik.OpenAccess.Runtime
	Help link : 
	ErrorCode : ‹‹‹40613›››
	ArrayBindIndex : ‹‹‹-1›››
	Number : ‹‹‹40613›››
	ObjectId : 
	Description : ‹‹‹Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '8EB0F76A-793D-44A4-8AF1-7D7DBD2431CF'.›››
	Data : ‹‹‹System.Collections.ListDictionaryInternal›››
	TargetSite : ‹‹‹Telerik.OpenAccess.RT.sql.Connection connect(Telerik.OpenAccess.Config.Sql.ConnectionString, Telerik.OpenAccess.SPI.PropertySet, Telerik.OpenAccess.ConnectionPoolType, OpenAccessRuntime.logging.LogEventStore)›››
	HResult : ‹‹‹-2146233088›››
	Stack Trace :    at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
	   at OpenAccessRuntime.Relational.sql.SqlDriver.InitializeFor(ConnectionString connectionString, Boolean noConnect, PropertySet props, DBDriver& driver, Connection& conn, ConnectionPoolType poolType)

		Inner Exception
		---------------
		Type : System.Data.SqlClient.SqlException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
		Message : ‹‹‹Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '8EB0F76A-793D-44A4-8AF1-7D7DBD2431CF'.›››
		Source : .Net SqlClient Data Provider
		Help link : 
		Errors : ‹‹‹System.Data.SqlClient.SqlErrorCollection›››
		ClientConnectionId : ‹‹‹8f148a95-10f9-4482-a109-40aa804ee853›››
		Class : ‹‹‹14›››
		LineNumber : ‹‹‹65536›››
		Number : ‹‹‹40613›››
		Procedure : ‹‹‹›››
		Server : ‹‹‹tcp:sitefinityserver.database.windows.net,1433›››
		State : ‹‹‹1›››
		ErrorCode : ‹‹‹-2146232060›››
		Data : ‹‹‹System.Collections.ListDictionaryInternal›››
		TargetSite : ‹‹‹Void .ctor(System.Data.ProviderBase.DbConnectionPoolIdentity, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SqlCredential, System.Object, System.String, System.Security.SecureString, Boolean, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SessionData, System.Data.ProviderBase.DbConnectionPool, System.String, Boolean, System.Data.SqlClient.SqlAuthenticationProviderManager)›››
		HResult : ‹‹‹-2146232060›››
		Stack Trace :    at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
		   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
		   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
		   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
		   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
		   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
		   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
		   at System.Data.SqlClient.SqlConnection.Open()
		   at OpenAccessRuntime.Intellitrace.OpenConnection(DbConnection connection, String connectionString, String id)
		   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)



Category: ErrorLog

Priority: 0

EventId: 90030

Severity: Error

Title:Enterprise Library Exception Handling

Machine: BRIMITPL-IMO

App Domain: /LM/W3SVC/2/ROOT-1-133764092455929219

ProcessId: 18428

Process Name: C:\Program Files\IIS Express\iisexpress.exe

Thread Name: 

Win32 ThreadId:23508

Extended Properties: 
----------------------------------------
----------------------------------------
ActivityId: 3c29bf26-57d2-45de-8fd6-f9beb778dc4a

Timestamp: 18.11.2024 13:16:58

Message: ‹‹‹Timestamp: 18.11.2024 13:16:58
Message: Telerik.OpenAccess.Exceptions.DataStoreException: Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '8EB0F76A-793D-44A4-8AF1-7D7DBD2431CF'. Telerik.OpenAccess.RT.sql.SQLException: Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '8EB0F76A-793D-44A4-8AF1-7D7DBD2431CF'. ---> System.Data.SqlClient.SqlException: Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '8EB0F76A-793D-44A4-8AF1-7D7DBD2431CF'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at OpenAccessRuntime.Intellitrace.OpenConnection(DbConnection connection, String connectionString, String id)
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   --- End of inner exception stack trace ---
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   at OpenAccessRuntime.Relational.sql.SqlDriver.InitializeFor(ConnectionString connectionString, Boolean noConnect, PropertySet props, DBDriver& driver, Connection& conn, ConnectionPoolType poolType) ---> Telerik.OpenAccess.RT.sql.SQLException: Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '8EB0F76A-793D-44A4-8AF1-7D7DBD2431CF'. ---> System.Data.SqlClient.SqlException: Database 'SitefinityDatabase2' on server 'sitefinityserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '8EB0F76A-793D-44A4-8AF1-7D7DBD2431CF'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at OpenAccessRuntime.Intellitrace.OpenConnection(DbConnection connection, String connectionString, String id)
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   --- End of inner exception stack trace ---
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   at OpenAccessRuntime.Relational.sql.SqlDriver.InitializeFor(ConnectionString connectionString, Boolean noConnect, PropertySet props, DBDriver& driver, Connection& conn, ConnectionPoolType poolType)
   --- End of inner exception stack trace ---
   at DynamicModule.ns.Wrapped_OpenAccessMetaDataProvider_56adb7e0f6784e8b9dae36e76b4acf2d.Initialize(String providerName, NameValueCollection config, Type managerType)
   at Telerik.Sitefinity.Data.ManagerBase`1.InstantiateProvider(IDataProviderSettings providerSettings, Type providerType, ExceptionPolicyName policy, Type managerType)
   at Telerik.Sitefinity.Data.ManagerBase`1.InstantiateProvider(IDataProviderSettings providerSettings, ExceptionPolicyName policy, Type managerType)
   at Telerik.Sitefinity.Data.ManagerBase`1.ResolveProvider(String providerName, String dataSourceName)
   at Telerik.Sitefinity.Data.ManagerBase`1.SetProvider(String providerName, String transactionName)
   at Telerik.Sitefinity.Data.Metadata.MetadataManager..ctor()
Category: 
Priority: -1
EventId: 0
Severity: Critical
Title:
Machine: BRIMITPL-IMO
App Domain: /LM/W3SVC/2/ROOT-1-133764092455929219
ProcessId: 18428
Process Name: C:\Program Files\IIS Express\iisexpress.exe
Thread Name: 
Win32 ThreadId:23508
Extended Properties: ›››

Category: ErrorLog

Priority: -1

EventId: 1

Severity: Information

Title:

Machine: BRIMITPL-IMO

App Domain: /LM/W3SVC/2/ROOT-1-133764092455929219

ProcessId: 18428

Process Name: C:\Program Files\IIS Express\iisexpress.exe

Thread Name: 

Win32 ThreadId:23508

Extended Properties: 
----------------------------------------
----------------------------------------
ActivityId: 65261238-2ac3-4478-829c-f7dd434931f2

Timestamp: 11/18/2024 1:17:32 PM

Message: HandlingInstanceID: 62df9663-2069-4ae5-97c7-d8daff394965
An exception of type 'Telerik.OpenAccess.OpenAccessException' occurred and was caught.
--------------------------------------------------------------------------------------
11/18/2024 14:17:32
Type : Telerik.OpenAccess.OpenAccessException, Telerik.OpenAccess, Version=2020.0.428.1, Culture=neutral, PublicKeyToken=7ce17eeaf1d59342
Message : ‹‹‹Telerik.OpenAccess.RT.sql.SQLException: Login failed for user 'IlyaMaisiuk'.›››
Source : Telerik.OpenAccess
Help link : 
InnerExceptions : ‹‹‹System.Exception[]›››
FailedObject : 
BackendError : ‹‹‹Telerik.OpenAccess.RT.sql.SQLException: Login failed for user 'IlyaMaisiuk'. ---> System.Data.SqlClient.SqlException: Login failed for user 'IlyaMaisiuk'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at OpenAccessRuntime.Intellitrace.OpenConnection(DbConnection connection, String connectionString, String id)
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   --- End of inner exception stack trace ---
   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
   at OpenAccessRuntime.DataObjects.tools.ant.DatabaseCreationTask.createDatabase()›››
Reason : ‹‹‹Runtime›››
CanRetry : ‹‹‹True›››
Data : ‹‹‹System.Collections.ListDictionaryInternal›››
TargetSite : ‹‹‹Void ThrowException(System.Exception)›››
HResult : ‹‹‹-2146233088›››
Stack Trace :    at Telerik.OpenAccess.SPI.Backends.ThrowException(Exception e)
   at OpenAccessRuntime.ExceptionWrapper.Throw()
   at OpenAccessRuntime.DataObjects.tools.ant.DataObjectsTaskBase.throwBuildException(String str, Exception e)
   at OpenAccessRuntime.DataObjects.tools.ant.DatabaseCreationTask.createDatabase()
   at OpenAccessRuntime.OpenAccessSchemaAdapter.CreateDatabase(Boolean checkOnly)
   at OpenAccessRuntime.SchemaHandlerImpl.Telerik.OpenAccess.ISchemaHandler.CreateDatabase()
   at Telerik.Sitefinity.Data.OA.OpenAccessConnection.UpgradeDatabaseSchema(ISchemaHandler schemaHandler, OpenAccessConnection connection)
   at Telerik.Sitefinity.Data.OA.OpenAccessConnection.UpgradeDatabase(Database database, OpenAccessConnection connection)
   at Telerik.Sitefinity.Data.OA.OpenAccessConnection.GetAndUpgradeMetadataDatabase(IConnectionStringSettings connectionSettings, OpenAccessConnection oaConnection, MetadataContainer metadataContainer, String appName, String moduleName, String& connString, Int32& previousBuild, Boolean isSecondCall)

Additional Info:

MachineName : BRIMITPL-IMO
TimeStamp : 11/18/2024 1:17:32 PM
FullName : Telerik.Sitefinity.Utilities, Version=15.2.8400.0, Culture=neutral, PublicKeyToken=b28c218413bdf563
AppDomainName : /LM/W3SVC/2/ROOT-1-133764092455929219
ThreadIdentity : 
WindowsIdentity : BRIMITPL-IMO\local-admin
Requested URL : https://localhost:44331/
	Inner Exception
	---------------
	Type : Telerik.OpenAccess.RT.sql.SQLException, Telerik.OpenAccess.Runtime, Version=2020.0.428.1, Culture=neutral, PublicKeyToken=7ce17eeaf1d59342
	Message : ‹‹‹Login failed for user 'IlyaMaisiuk'.›››
	Source : Telerik.OpenAccess.Runtime
	Help link : 
	ErrorCode : ‹‹‹18456›››
	ArrayBindIndex : ‹‹‹-1›››
	Number : ‹‹‹18456›››
	ObjectId : 
	Description : ‹‹‹Login failed for user 'IlyaMaisiuk'.›››
	Data : ‹‹‹System.Collections.ListDictionaryInternal›››
	TargetSite : ‹‹‹Telerik.OpenAccess.RT.sql.Connection connect(Telerik.OpenAccess.Config.Sql.ConnectionString, Telerik.OpenAccess.SPI.PropertySet, Telerik.OpenAccess.ConnectionPoolType, OpenAccessRuntime.logging.LogEventStore)›››
	HResult : ‹‹‹-2146233088›››
	Stack Trace :    at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)
	   at OpenAccessRuntime.DataObjects.tools.ant.DatabaseCreationTask.createDatabase()

		Inner Exception
		---------------
		Type : System.Data.SqlClient.SqlException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
		Message : ‹‹‹Login failed for user 'IlyaMaisiuk'.›››
		Source : .Net SqlClient Data Provider
		Help link : 
		Errors : ‹‹‹System.Data.SqlClient.SqlErrorCollection›››
		ClientConnectionId : ‹‹‹7425f096-088e-413e-bd6d-4728e4ef51d4›››
		Class : ‹‹‹14›››
		LineNumber : ‹‹‹65536›››
		Number : ‹‹‹18456›››
		Procedure : ‹‹‹›››
		Server : ‹‹‹tcp:sitefinityserver.database.windows.net,1433›››
		State : ‹‹‹1›››
		ErrorCode : ‹‹‹-2146232060›››
		Data : ‹‹‹System.Collections.ListDictionaryInternal›››
		TargetSite : ‹‹‹Void .ctor(System.Data.ProviderBase.DbConnectionPoolIdentity, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SqlCredential, System.Object, System.String, System.Security.SecureString, Boolean, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SessionData, System.Data.ProviderBase.DbConnectionPool, System.String, Boolean, System.Data.SqlClient.SqlAuthenticationProviderManager)›››
		HResult : ‹‹‹-2146232060›››
		Stack Trace :    at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
		   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
		   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
		   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
		   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
		   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
		   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
		   at System.Data.SqlClient.SqlConnection.Open()
		   at OpenAccessRuntime.Intellitrace.OpenConnection(DbConnection connection, String connectionString, String id)
		   at Telerik.OpenAccess.RT.Adonet2Generic.Impl.DBDriver.connect(ConnectionString connectionString, PropertySet driverProps, ConnectionPoolType poolType, LogEventStore pes)



Category: ErrorLog

Priority: 0

EventId: 9010

Severity: Warning

Title:Enterprise Library Exception Handling

Machine: BRIMITPL-IMO

App Domain: /LM/W3SVC/2/ROOT-1-133764092455929219

ProcessId: 18428

Process Name: C:\Program Files\IIS Express\iisexpress.exe

Thread Name: 

Win32 ThreadId:3088

Extended Properties: 
----------------------------------------
----------------------------------------
ActivityId: 65261238-2ac3-4478-829c-f7dd434931f2

Timestamp: 11/18/2024 1:17:43 PM

Message: HandlingInstanceID: 43d8bc25-482a-48fe-ad7d-1b56f114f453
An exception of type 'System.Threading.ThreadAbortException' occurred and was caught.
-------------------------------------------------------------------------------------
11/18/2024 14:17:43
Type : System.Threading.ThreadAbortException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Message : ‹‹‹Thread was being aborted.›››
Source : Unity_ILEmit_DynamicClasses
Help link : 
ExceptionState : ‹‹‹System.Web.HttpApplication+CancelModuleException›››
Data : ‹‹‹System.Collections.ListDictionaryInternal›››
TargetSite : ‹‹‹Telerik.Microsoft.Practices.Unity.InterceptionExtension.IMethodReturn <Initialize_DelegateImplementation>__97(Telerik.Microsoft.Practices.Unity.InterceptionExtension.IMethodInvocation, Telerik.Microsoft.Practices.Unity.InterceptionExtension.GetNextInterceptionBehaviorDelegate)›››
HResult : ‹‹‹-2146233040›››
Stack Trace :    at DynamicModule.ns.Wrapped_OpenAccessMetaDataProvider_56adb7e0f6784e8b9dae36e76b4acf2d.<Initialize_DelegateImplementation>__97(IMethodInvocation inputs, GetNextInterceptionBehaviorDelegate getNext)
   at Telerik.Microsoft.Practices.Unity.InterceptionExtension.PolicyInjectionBehavior.<>c__DisplayClass3_0.<Invoke>b__0(IMethodInvocation policyInjectionInput, GetNextHandlerDelegate policyInjectionInputGetNext)
   at DynamicModule.ns.Wrapped_OpenAccessMetaDataProvider_56adb7e0f6784e8b9dae36e76b4acf2d.Initialize(String providerName, NameValueCollection config, Type managerType)
   at Telerik.Sitefinity.Data.ManagerBase`1.InstantiateProvider(IDataProviderSettings providerSettings, Type providerType, ExceptionPolicyName policy, Type managerType)

Additional Info:

MachineName : BRIMITPL-IMO
TimeStamp : 11/18/2024 1:17:43 PM
FullName : Telerik.Sitefinity.Utilities, Version=15.2.8400.0, Culture=neutral, PublicKeyToken=b28c218413bdf563
AppDomainName : /LM/W3SVC/2/ROOT-1-133764092455929219
ThreadIdentity : 
WindowsIdentity : BRIMITPL-IMO\local-admin
Requested URL : https://localhost:44331/


Category: ErrorLog

Priority: 0

EventId: 90030

Severity: Error

Title:Enterprise Library Exception Handling

Machine: BRIMITPL-IMO

App Domain: /LM/W3SVC/2/ROOT-1-133764092455929219

ProcessId: 18428

Process Name: C:\Program Files\IIS Express\iisexpress.exe

Thread Name: 

Win32 ThreadId:3088

Extended Properties: 
----------------------------------------
----------------------------------------
ActivityId: 65261238-2ac3-4478-829c-f7dd434931f2

Timestamp: 11/18/2024 1:17:43 PM

Message: HandlingInstanceID: 97bfc1dc-3d00-4b18-acbc-5b981bede1ff
An exception of type 'System.Web.HttpException' occurred and was caught.
------------------------------------------------------------------------
11/18/2024 14:17:43
Type : System.Web.HttpException, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Message : ‹‹‹Request timed out.›››
Source : 
Help link : 
WebEventCode : ‹‹‹3001›››
ErrorCode : ‹‹‹-2147467259›››
Data : ‹‹‹System.Collections.ListDictionaryInternal›››
TargetSite : 
HResult : ‹‹‹-2147467259›››
Stack Trace : The stack trace is unavailable.
Additional Info:

MachineName : BRIMITPL-IMO
TimeStamp : 11/18/2024 1:17:43 PM
FullName : Telerik.Sitefinity.Utilities, Version=15.2.8400.0, Culture=neutral, PublicKeyToken=b28c218413bdf563
AppDomainName : /LM/W3SVC/2/ROOT-1-133764092455929219
ThreadIdentity : 
WindowsIdentity : BRIMITPL-IMO\local-admin
Requested URL : https://localhost:44331/


Category: ErrorLog

Priority: 0

EventId: 90000

Severity: Error

Title:Enterprise Library Exception Handling

Machine: BRIMITPL-IMO

App Domain: /LM/W3SVC/2/ROOT-1-133764092455929219

ProcessId: 18428

Process Name: C:\Program Files\IIS Express\iisexpress.exe

Thread Name: 

Win32 ThreadId:3088

Extended Properties: 
----------------------------------------
